install.packages("httpuv")
require('devtools')
#install_github('rstudio/shiny')
install_github('wch/shiny-gridster')
install_github('ramnathv/dashifyr')
install_github('ramnathv/rHighCharts')

require('dashifyr')
demoapp = system.file('demo', package = 'dashifyr')
shiny::runApp(demoapp)
